/**
 * export-css.ts
 *
 * デザイントークンを Hugo 向けの CSS カスタムプロパティとして書き出すスクリプト。
 *
 * 使い方:
 *   npx tsx export-css.ts
 *   npx tsx export-css.ts --theme kawaii
 *   npx tsx export-css.ts --out ../my-hugo-blog/assets/css/tokens.css
 *   npx tsx export-css.ts --all --out ../my-hugo-blog/assets/css/tokens.css
 *
 * オプション:
 *   --theme <n>  出力するテーマ名 (mono | kawaii、デフォルト: mono)
 *   --out <path>    出力先ファイルパス (デフォルト: ./dist/tokens.css)
 *   --all           全テーマを data-theme 属性セレクタで出力
 */

import fs   from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { monoTheme } from "./tokens.mono";
import { kawaiiTheme } from "./tokens.kawaii";
import type { Theme } from "./types";

// ============================================================
// 全テーマの登録
// ============================================================
export const themes: Record<string, Theme> = {
  mono:   monoTheme,
  kawaii: kawaiiTheme,
};

// ============================================================
// コア変換ロジック（export してテスト可能にする）
// ============================================================

/**
 * camelCase キーを CSS 変数名用の kebab-case に変換する。
 * 例: accentHover → accent-hover
 */
export function toKebabCase(key: string): string {
  return key.replace(/([A-Z])/g, "-$1").toLowerCase();
}

/**
 * Theme オブジェクトを CSS カスタムプロパティの文字列に変換する。
 * 変数名は --ds-<category>-<key> の形式。
 * 例: --ds-color-accent, --ds-scale-md, --ds-radius-full
 */
export function themeToCssVars(theme: Theme): string {
  const lines: string[] = [];

  // colors
  for (const [key, value] of Object.entries(theme.colors)) {
    lines.push(`  --ds-color-${toKebabCase(key)}: ${value};`);
  }
  lines.push("");

  // typography
  for (const [key, value] of Object.entries(theme.typography)) {
    lines.push(`  --ds-font-${key}: ${value};`);
  }
  lines.push("");

  // scale (spacing)
  for (const [key, value] of Object.entries(theme.scale)) {
    lines.push(`  --ds-scale-${key}: ${value};`);
  }
  lines.push("");

  // radius
  for (const [key, value] of Object.entries(theme.radius)) {
    lines.push(`  --ds-radius-${key}: ${value};`);
  }
  lines.push("");

  // font import URL
  lines.push(`  --ds-font-import: url('${theme.fontImport}');`);

  return lines.join("\n");
}

/**
 * 単一テーマを :root セレクタで出力する。
 * タイムスタンプは差し替え可能にしてテストでの安定性を確保する。
 */
export function buildSingleTheme(theme: Theme, timestamp = new Date().toISOString()): string {
  return [
    `/* Design System Tokens — ${theme.label} */`,
    `/* Auto-generated by export-css.ts. Do not edit manually. */`,
    `/* Generated at: ${timestamp} */`,
    ``,
    `:root {`,
    themeToCssVars(theme),
    `}`,
    ``,
  ].join("\n");
}

/**
 * 全テーマを data-theme 属性セレクタで出力する。
 *
 * Hugo テンプレート側:  <html data-theme="mono">
 * JS での切り替え:      document.documentElement.setAttribute('data-theme', 'kawaii')
 */
export function buildAllThemes(
  themeMap: Record<string, Theme> = themes,
  defaultThemeName = "mono",
  timestamp = new Date().toISOString(),
): string {
  const blocks: string[] = [
    `/* Design System Tokens — All Themes */`,
    `/* Auto-generated by export-css.ts. Do not edit manually. */`,
    `/* Generated at: ${timestamp} */`,
    ``,
    `/* Usage: <html data-theme="mono"> or <html data-theme="kawaii"> */`,
    `/* JS:     document.documentElement.setAttribute('data-theme', 'kawaii') */`,
    ``,
  ];

  for (const [name, theme] of Object.entries(themeMap)) {
    const selectors =
      name === defaultThemeName
        ? `:root,\n[data-theme="${name}"]`
        : `[data-theme="${name}"]`;

    blocks.push(`/* ---- ${theme.label} ---- */`);
    blocks.push(`${selectors} {`);
    blocks.push(themeToCssVars(theme));
    blocks.push(`}`);
    blocks.push(``);
  }

  return blocks.join("\n");
}

// ============================================================
// CLI
// ============================================================
export function parseArgs(argv: string[]): { theme: string; out: string; all: boolean } {
  const args = argv.slice(2);
  const result = { theme: "mono", out: "./dist/tokens.css", all: false };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--theme" && args[i + 1]) result.theme = args[++i];
    if (args[i] === "--out"   && args[i + 1]) result.out   = args[++i];
    if (args[i] === "--all")                  result.all   = true;
  }

  return result;
}

export function main() {
  const { theme: themeName, out, all } = parseArgs(process.argv);

  const outDir = path.dirname(path.resolve(out));
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
    console.log(`📁 Created directory: ${outDir}`);
  }

  let css: string;

  if (all) {
    css = buildAllThemes();
    console.log(`🎨 Exporting all themes...`);
  } else {
    const theme = themes[themeName];
    if (!theme) {
      console.error(`❌ Unknown theme: "${themeName}". Available: ${Object.keys(themes).join(", ")}`);
      process.exit(1);
    }
    css = buildSingleTheme(theme);
    console.log(`🎨 Exporting theme: ${theme.label}`);
  }

  fs.writeFileSync(path.resolve(out), css, "utf-8");
  console.log(`✅ Written to: ${path.resolve(out)}`);
  console.log(`\n📋 Hugo の layouts/partials/head.html などで読み込み:`);
  console.log(`   <link rel="stylesheet" href="{{ "theme/tokens.css" | relURL }}">`);
}

const isDirectExecution =
  process.argv[1] != null &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectExecution) {
  main();
}
